name: Uni-Dock/Tools Build Image Workflow
on:
  push:
    branches:
      - main

jobs:
  build_unidock_docker_image:
    if: github.repository_owner == 'dptech-corp'
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: dptechnology
        password: ${{ secrets.DOCKERHUB_PAT }}

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: build and push container
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64
        tags: dptechnology/unidock:${{ steps.short-sha.outputs.sha }},dptechnology/unidock:latest
        file: containers/Dockerfile
        context: "{{defaultContext}}:unidock"
        push: true

  build_unidock_tools_docker_image:
    if: github.repository_owner == 'dptech-corp'
    needs: build_unidock_docker_image
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: dptechnology
        password: ${{ secrets.DOCKERHUB_PAT }}

    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: build and push container
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64
        tags: dptechnology/unidock_tools:${{ steps.short-sha.outputs.sha }},dptechnology/unidock_tools:latest
        file: unidock_tools/containers/Dockerfile
        push: true