name: auto build docker image for vina-gpu
on:
  pull_request:
    branches: [ develop ]

jobs:

  docker_auto_build:
    name: build and push Docker image to DP docker image repo 
    runs-on: self-hosted
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: login
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DPLC_REGISTRY }} 
        username: ${{ secrets.DPLC_USERNAME }} 
        password: ${{ secrets.DPLC_PASSWORD }}
    
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./container/internal_testing.dockerfile
        push: true
        tags: ${{ secrets.DPLC_REGISTRY }}/dplc/vina_gpu:autobuild-${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DPLC_REGISTRY }}/dplc/vina_gpu:latest
        cache-to: type=inline

  send_email:
    name: send email to inform vina-gpu group members
    runs-on: ubuntu-latest
    needs: [ docker_auto_build ]
    steps:
    - name: send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.feishu.cn
        server_port: 465
        username: ${{ secrets.ZH_MAILUSERNAME }}
        password: ${{ secrets.ZH_MAILPASSWORD }}
        subject: Auto Build For Vina-GPU
        body: ${{ secrets.DPLC_REGISTRY }}/dplc/vina_gpu:autobuild-${{ github.sha }}
        to: ${{ secrets.VINAGPU_MAIL_RECEIVER_LIST }}
        from: GitHub Actions
        content_type: text
